<div class="row">
          <div class="col card-deck">
          <div class="card col-12 col-md-4 text-white mb-3 p-0">
                <div class="card-header bg-dark">Visualisation rapide</div>
                <div class="card-body bg-white text-dark">
                  <p class="card-text ">Pour voir tout de suite votre site</p>
                  <a href="#" class="btn btn-primary w-100">Afficher votre site</a>
                </div>
                <div class="card-header bg-dark">Action rapides</div>
                <div class="card-body d-flex flex-md-column">
                  <a href="#" class="card-link"><i class="far fa-newspaper"></i> Ajouter un article</a>
                  <a href="#" class="card-link m-0"><i class="far fa-file"></i> Ajouter une page</a>
                  <a href="#" class="card-link m-0"><i class="fas fa-user"></i> Ajouter un utilisateur</a>
                </div>
            </div>
            <div class="card col-12 col-md-8 text-white mb-3 p-0">
                <div class="card-header bg-dark">Article rapide</div>
                <div class="card-body bg-white text-dark">
                    <form>
                        <div class="form-group">
                          <label for="formGroupExampleInput">Titre de l'article</label>
                          <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Titre">
                        </div>
                        <div class="mb-3">
                            <label for="validationTextarea">Text de l'article</label>
                            <textarea class="form-control" id="validationTextarea" required></textarea>
                        </div>
                        <div class="row">
                            <div class="form-check">
                                <input class="form-check-input position-static" type="radio" name="blankRadio" id="blankRadio1" value="option1" aria-label="...">
                                <label class="form-check-label mr-3" for="gridCheck">
                                    Publier
                                  </label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input position-static" type="radio" name="blankRadio" id="blankRadio1" value="option1" aria-label="...">
                                <label class="form-check-label" for="gridCheck">
                                    Brouillon
                                  </label>
                            </div>
                        </div>
                        <button type="button" class="btn btn-primary mt-2">Enregistrer</button>
                    </form>
                </div>
          </div>
          </div>
        </div>
        <div class="row">
          <div class="col card-deck">
          <div class="card col-12 col-md-7 text-white mb-3 p-0">
            <div class="card-header bg-dark">Liste des derniers articles</div>
            <div class="card-body text-dark">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <blockquote class="blockquote mb-0">
                <p>Article 1</p>
                <p>Début de l'article</p>
                <footer class="blockquote-footer">Auteur <cite title="Source Title">Fred</cite></footer>
              </blockquote>
            </li>
            <li class="list-group-item">
                <blockquote class="blockquote mb-0">
                <p>Article 2</p>
                <p>Début de l'article</p>
                <footer class="blockquote-footer">Auteur <cite title="Source Title">Fred</cite></footer>
              </blockquote>
            </li>
            <li class="list-group-item">
                <blockquote class="blockquote mb-0">
                <p>Article 3</p>
                <p>Début de l'article</p>
                <footer class="blockquote-footer">Auteur <cite title="Source Title">Fred</cite></footer>
              </blockquote>
            </li>
            <li class="list-group-item">
                <blockquote class="blockquote mb-0">
                <p>Article 4</p>
                <p>Début de l'article</p>
                <footer class="blockquote-footer">Auteur <cite title="Source Title">Fred</cite></footer>
              </blockquote>
            </li>
            </ul>
            </div>
          </div>
          <div class="card col-12 col-md-5 text-white mb-3 p-0">
              <div class="card-header bg-dark">Liste des derniers articles</div>
              <div class="card-body text-dark">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <blockquote class="blockquote mb-0">
                  <p>Début de l'article</p>
                  <footer class="blockquote-footer text-right">De <cite title="Source Title">Jean Bob</cite></footer>
                </blockquote>
              </li>
              <li class="list-group-item">
                  <blockquote class="blockquote mb-0">
                  <p>Début de l'article</p>
                  <footer class="blockquote-footer text-right">Auteur <cite title="Source Title">Jean Karime</cite></footer>
                </blockquote>
              </li>
              <li class="list-group-item">
                  <blockquote class="blockquote mb-0">
                  <p>Début de l'article</p>
                  <footer class="blockquote-footer text-right">Auteur <cite title="Source Title">Jean Fred</cite></footer>
                </blockquote>
              </li>
              <li class="list-group-item">
                  <blockquote class="blockquote mb-0">
                  <p>Début de l'article</p>
                  <footer class="blockquote-footer text-right">Auteur <cite title="Source Title">Jeanne Sabine</cite></footer>
                </blockquote>
              </li>
              </ul>
            </div>
          </div>
          </div>
        </div>