<script src="js/main.js"></script>
<div class="row m-3">
    <table class="table col table-striped table-dark">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Nom d'utilisateur</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Prénom</th>
                    <th scope="col">Nom</th>
                    <th scope="col">Date de création</th>
                    <th scope="col">Dernière connexion</th>
                    <th scope="col">Rank</th>
                    <th scope="col">Avatar</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($usersData as $userData): ?>
                <tr>
                    <td><?= $userData['id']?></td>
                    <td><?= $userData['username']?></td>
                    <td><?= $userData['email']?></td>
                    <td><?= $userData['firstname']?></td>
                    <td><?= $userData['lastname']?></td>
                    <td><?= $userData['created_date']?></td>
                    <td><?= $userData['last_login_date']?></td>
                    <td><?= $userData['rank']?></td>
                    <td><?= (file_exists('../images/users/'.$userData['avatar']) && $userData['avatar'] != NULL)?'<img width="150" src="../images/users/' . $userData['avatar'] . '">':'Avatar inexistant'?></td>
                    <td><a href="delUser.php?id=<?= $userData['id']?>" class="delete"><i class="fas fa-trash-alt mr-2"></i></a><a href="deleteUser.php?id<?= $userData['id'] ?>"><i class="fas fa-edit"></i></a></td>
                </tr>
                <?php endforeach ?>
            </tbody>
    </table>
</div>
<div class="modal" id="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Supression de l'utilisateur</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Êtes-vous sur de vouloir suprimmez cette utilisateur?</p>
        <p>Cette action est irréversible !</p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary button">Oui</a>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
      </div>
    </div>
  </div>
</div>