<script src="js/main.js"></script>
<div class="row m-3">
    <table class="table col table-striped table-dark">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Titre</th>
                    <th scope="col">Contenue</th>
                    <th scope="col">Sous-titre</th>
                    <th scope="col">Image</th>
                    <th scope="col">Date de création</th>
                    <th scope="col">Date de publication</th>
                    <th scope="col">Status</th>
                    <th scope="col">Catégorie</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($articles as $article): ?>
                <tr>
                    <td><?= $article['id']?></td>
                    <td><?= $article['title']?></td>
                    <td class="w-25"><?= $article['content']?></td>
                    <td><?= $article['substitle']?></td>
                    <td><?= (file_exists('../images/articles/'.$article['image']) && $article['image'] != NULL)?'<img width="150" src="../images/articles/' . $article['image'] . '">':'Image inexistante'?></td>
                    <td><?= $article['created_date']?></td>
                    <td><?= $article['published_date']?></td>
                    <td><?= ($article['status'] == 0)? 'Privée' : 'Public'?></td>
                    <td><?= $article['name']?></td>
                    <td><a href="delArticle.php?id=<?= $article['id']?>" class="delete"><i class="fas fa-trash-alt mr-2"></i></a><a href="listArticle.php?id=<?= $article['id'] ?>" class="edit"><i class="fas fa-edit"></i></a></td>
                </tr>
                <?php endforeach ?>
            </tbody>
    </table>
</div>
<div class="modal" id="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Supression d'article'</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Êtes-vous sur de vouloir suprimmez cette article?</p>
        <p>Cette action est irreversible !</p>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary button">Oui</a>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
      </div>
    </div>
  </div>
</div>