<div class="container">
<div class="row">
  <div class="card col text-white mb-3 mt-3 p-0">
      <div class="card-header bg-dark">Logging</div>
      <div class="card-body bg-white text-dark">
          <?php if($error != ''):?>
          <div class="alert alert-danger" role="alert">
          <?= $error ?>
          </div>
          <?php endif;?>
          <form action="login.php" method="POST">
              <div class="form-group">
                  <label for="validationTextarea">E-mail</label>
                  <input type="email" name="email" value="<?= $email ?>" class="form-control" id="formGroupExampleInput" required>
              </div>
              <div class="mb-3">
                <label for="formGroupExampleInput">Mot de passe</label>
                <input type="password" name="password" class="form-control" id="formGroupExampleInput" required>
              </div>
              <input type="submit" value="Enregistré">
          </form>
      </div>
  </div>
</div>
</div>       