<header class="masthead" style="background-image: url('images/articles/<?= $article['image'] ?>')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1><?= $article['title'] ?></h1>
            <h2 class="subheading"><?= $article['substitle']?></h2>
            <span class="meta">Posted by
              <a href="#">Start Bootstrap</a>
              on <?= $article['created_date']?></span>
          </div>
        </div>
      </div>
    </div>
  </header>
<article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <?= $article['content'] ?>
        </div>
      </div>
    </div>
  </article>