<!-- Page Header -->
<header class="masthead" style="background-image: url('images/background.jpg')">
<div class="overlay"></div>
<div class="container">
    <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
        <div class="site-heading">
        <h1>Devenir millionaire en 5 étapes</h1>
        <span class="subheading">La 3ème va vous surprendre</span>
        </div>
    </div>
    </div>
</div>
</header>

<!-- Main Content -->
<div class="container">
<div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
    <?php foreach($articles as $article): ?>
    <div class="post-preview">
        <a href="article.php?id=<?=$article['id']?>">
        <h2 class="post-title">
            <?= $article['title'] ?>
        </h2>
        <h3 class="post-subtitle">
            <?= $article['substitle'] ?>
        </h3>
        </a>
        <p class="post-meta">Posted by
        <a href="#">Start Bootstrap</a>
        on <?= $article['created_date'] ?></p>
    </div>
    <hr>
    <?php endforeach ?>
    <!-- Pager -->
    <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
    </div>
    </div>
</div>
</div>
